# Generated by Django 2.0 on 2017-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batchsystem',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batchsystem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('batchsystem', models.CharField(max_length=100)),
                ('login_node', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'cluster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hw_info', models.TextField(blank=True, null=True)),
                ('hw_info_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('hw_info', models.TextField()),
                ('created', models.DateField()),
                ('cpu', models.CharField(blank=True, max_length=150, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_sockets', models.IntegerField(blank=True, null=True)),
                ('accelerator', models.CharField(blank=True, max_length=250, null=True)),
                ('accelerator_type', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('memory_modules', models.IntegerField(blank=True, null=True)),
                ('hdd_size', models.IntegerField(blank=True, null=True)),
                ('hdd', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NormalizedResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'normalized_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('test_config_id', models.IntegerField(blank=True, null=True)),
                ('job_id', models.CharField(blank=True, max_length=150, null=True)),
                ('result_detail', models.TextField(blank=True, null=True)),
                ('result', models.FloatField(blank=True, null=True)),
                ('test_config_version_hash', models.CharField(blank=True, max_length=150, null=True)),
                ('submit', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultsNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'results_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin', models.DateTimeField()),
                ('repeat', models.TextField(blank=True, null=True)),
                ('test_id', models.IntegerField(blank=True, null=True)),
                ('test_config_id', models.IntegerField(blank=True, null=True)),
                ('nodes', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('config', models.TextField(blank=True, null=True)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('configfile_ending', models.CharField(blank=True, max_length=10, null=True)),
                ('needs_configfile', models.NullBooleanField()),
                ('edited', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestConfigHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_diff', models.TextField(blank=True, null=True)),
                ('parameter_diff', models.TextField(blank=True, null=True)),
                ('hash', models.CharField(max_length=150, unique=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('was_built', models.NullBooleanField()),
            ],
            options={
                'db_table': 'test_config_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestconfigNodetypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'testconfig_nodetypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('run_script', models.TextField(blank=True, null=True)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('multi_node', models.BooleanField()),
                ('analysis_script', models.TextField(blank=True, null=True)),
                ('build_script', models.TextField(blank=True, null=True)),
                ('needs_building', models.NullBooleanField()),
            ],
            options={
                'db_table': 'tests',
                'managed': False,
            },
        ),
    ]
